# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0009_auto_20170603_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='portrait_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
