# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0010_person_portrait_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_id', models.CharField(help_text=b'Peoples Assembly ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contactmps.Party'),
        ),
    ]
