# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0011_auto_20170606_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituencyBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_id', models.CharField(help_text=b'Peoples Assembly ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='constituency_branches',
            field=models.ManyToManyField(to='contactmps.ConstituencyBranch'),
        ),
    ]
