# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0012_auto_20170607_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituencybranch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constituencybranch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
