# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0014_auto_20170607_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='body',
            new_name='body_txt',
        ),
    ]
