# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:23
from __future__ import unicode_literals

import contactmps.models
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Email = apps.get_model('contactmps', 'Email')
    for obj in Email.objects.all():
        obj.sender_secret = contactmps.models.secure_random_string()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0015_auto_20170620_1604'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='SenderQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='sender_secret',
            field=models.CharField(blank=True, default=contactmps.models.secure_random_string, max_length=100, unique=False),
        ),
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='email',
            name='sender_secret',
            field=models.CharField(max_length=100, unique=True, null=False),
        ),
        migrations.AddField(
            model_name='senderqa',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactmps.Email'),
        ),
        migrations.RunSQL(migrations.RunSQL.noop,
                          reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
