# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from contactmps.models import Campaign


def forwards(apps, schema_editor):
    Campaign = apps.get_model("contactmps", "Campaign")
    psam = Campaign(slug='psam')
    psam.save()
    newsmedia = Campaign(slug='newsmedia')
    newsmedia.save()
    secretballot = Campaign(slug='secretballot')
    secretballot.save()

    Email = apps.get_model('contactmps', 'Email')
    for email in Email.objects.all():
        if 'Parliament has failed to hold' in email.body_txt:
            email.campaign = psam
        if 'secret ballot' in email.body_txt:
            email.campaign = secretballot
        if 'In particular the upcoming vote of no confidence' in email.body_txt:
            email.campaign = newsmedia
        email.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0017_auto_20170720_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contactmps.Campaign'),
        ),
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='email',
            name='campaign',
            field=models.ForeignKey(Campaign),
        ),
    ]
