# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0019_auto_20170801_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_template',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='email_detail_template',
        ),
    ]
