# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0021_auto_20170801_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='divert_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contactmps.Campaign'),
        ),
    ]
