# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0022_auto_20170803_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='include_link_in_email',
            field=models.BooleanField(default=False),
        ),
    ]
