# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0024_committee'),
    ]

    operations = [
        migrations.RenameModel('Person', 'Entity'),
        migrations.RenameField('ContactDetail', 'person', 'entity'),
        migrations.RenameField('Email', 'to_person', 'to_entity'),
        migrations.RenameField(
            model_name='campaign',
            old_name='load_all_persons',
            new_name='load_all_entities',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='load_neglected_persons',
            new_name='load_neglected_entities',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='divert_emails',
            field=models.BooleanField(default=False, help_text=b'all emails towards parliament for that campaign will instead go to our webapps address and not to the actual recipient'),
        ),
    ]
