# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0025_auto_20180515_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='type',
            field=models.CharField(help_text=b"Type of contact detail, e.g. 'email'. This is used to find addresses by type for sending to the appropriate contacts.", max_length=40),
        ),
        migrations.AlterField(
            model_name='entity',
            name='constituency_branches',
            field=models.ManyToManyField(blank=True, to='contactmps.ConstituencyBranch'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='in_national_assembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='pa_id',
            field=models.CharField(blank=True, help_text=b'Peoples Assembly ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='pa_url',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactmps.Party'),
        ),
    ]
