# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contactmps', '0027_auto_20180515_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
