# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0028_campaign_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='sites',
            field=models.ForeignKey(blank=True, help_text=b'Right now you must have exactly one site per campaign otherwise the campaign will break.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
