# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contactmps', '0029_auto_20180515_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='sites',
        ),
        migrations.AddField(
            model_name='campaign',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text=b'Right now you must have exactly one campaign per site otherwise the campaign will break.', null=True, to='sites.Site'),
        ),
    ]
