# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0031_auto_20180515_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='moderate',
            field=models.BooleanField(default=1, help_text=b'Moderate the submission'),
        ),
    ]
