# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0032_email_moderate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='moderate',
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_moderation',
            field=models.BooleanField(default=False, help_text=b'moderate email submissions'),
        ),
    ]
