# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0033_auto_20180521_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_sent',
            field=models.BooleanField(default=False, help_text=b'Has the submission been sent'),
        ),
        migrations.AddField(
            model_name='email',
            name='moderated',
            field=models.BooleanField(default=False, help_text=b'Has the submission being moderated'),
        ),
    ]
