# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0034_auto_20180530_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='moderated',
        ),
        migrations.AddField(
            model_name='email',
            name='is_moderated',
            field=models.BooleanField(default=False, help_text=b'Has the submission been moderated'),
        ),
    ]
