# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmps', '0035_auto_20180530_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_endorsed',
            field=models.BooleanField(default=False, help_text=b'moderation outcome'),
        ),
    ]
